-- Learnly MVP database preparation.
-- Keep the schema simple; add auth/RLS after the core demo works.

create table if not exists learner_profiles (
    user_id text primary key,
    language text not null check (language in ('en', 'ta')),
    level integer not null default 1,
    xp integer not null default 0,
    streak integer not null default 0,
    reading_accuracy integer not null default 0,
    reading_fluency integer not null default 0,
    spelling integer not null default 0,
    sentence_formation integer not null default 0,
    current_difficulty text not null default 'medium'
        check (current_difficulty in ('easy', 'medium', 'hard')),
    weak_skill text
);

create table if not exists exercises (
    exercise_id text primary key,
    language text not null check (language in ('en', 'ta')),
    exercise_type text not null,
    expected_text text not null,
    difficulty text not null check (difficulty in ('easy', 'medium', 'hard'))
);

create table if not exists attempts (
    id bigint generated by default as identity primary key,
    user_id text,
    exercise_id text not null,
    language text not null check (language in ('en', 'ta')),
    expected_text text not null,
    student_response text not null,
    score integer not null check (score between 0 and 100),
    accuracy integer not null check (accuracy between 0 and 100),
    fluency integer not null check (fluency between 0 and 100),
    feedback text not null,
    created_at timestamptz not null default now()
);

create table if not exists progress (
    id bigint generated by default as identity primary key,
    user_id text not null,
    skill text not null,
    score integer not null check (score between 0 and 100),
    difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
    created_at timestamptz not null default now()
);
